for_web_interfece/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\CommonController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');
Route::redirect('admin/', 'home');
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::name('admin.')->middleware('role:admin')->group(function () {

    Route::get('/employees', [CommonController::class, 'employees']);
    Route::get('/employees/{id}', [CommonController::class, 'history'])->name('employee-history');
    Route::get('/wanted-employees', [CommonController::class, 'wanteds']);
    Route::get('/report', [CommonController::class, 'report']);
    Route::get('/dashboard', [CommonController::class, 'index']);
    Route::get('/stop-searching/{id}', [CommonController::class, 'stopSearching'])->name('stop-searching');
    Route::post('/search', [CommonController::class, 'search'])->name('search');
    Route::post('/add-employee', [CommonController::class, 'employeeAdd'])->name('add-employee');


    Route::get('/home', function () {
        return redirect('/dashboard');
    });
    Route::get('/dashboard/v1', function () {
        return view('pages/dashboard-v1');
    });
    Route::get('/dashboard/v2', function () {
        return view('pages/dashboard-v2');
    });
    // Route::get('/dashboard', function () {
    //     return view('pages/dashboard-v3');
    // });
    Route::get('/email/inbox', function () {
        return view('pages/email-inbox');
    });
    Route::get('/email/compose', function () {
        return view('pages/email-compose');
    });
    Route::get('/email/detail', function () {
        return view('pages/email-detail');
    });
    Route::get('/widget', function () {
        return view('pages/widget');
    });
    Route::get('/ui/general', function () {
        return view('pages/ui-general');
    });
    Route::get('/ui/typography', function () {
        return view('pages/ui-typography');
    });
    Route::get('/ui/tabs-accordions', function () {
        return view('pages/ui-tabs-accordions');
    });
    Route::get('/ui/unlimited-nav-tabs', function () {
        return view('pages/ui-unlimited-nav-tabs');
    });
    Route::get('/ui/modal-notification', function () {
        return view('pages/ui-modal-notification');
    });
    Route::get('/ui/widget-boxes', function () {
        return view('pages/ui-widget-boxes');
    });
    Route::get('/ui/media-object', function () {
        return view('pages/ui-media-object');
    });
    Route::get('/ui/buttons', function () {
        return view('pages/ui-buttons');
    });
    Route::get('/ui/icons', function () {
        return view('pages/ui-icons');
    });
    Route::get('/ui/simple-line-icons', function () {
        return view('pages/ui-simple-line-icons');
    });
    Route::get('/ui/ionicons', function () {
        return view('pages/ui-ionicons');
    });
    Route::get('/ui/tree-view', function () {
        return view('pages/ui-tree-view');
    });
    Route::get('/ui/language-bar-icon', function () {
        return view('pages/ui-language-bar-icon');
    });
    Route::get('/ui/social-buttons', function () {
        return view('pages/ui-social-buttons');
    });
    Route::get('/ui/intro-js', function () {
        return view('pages/ui-intro-js');
    });
    Route::get('/bootstrap-4', function () {
        return view('pages/bootstrap-4');
    });
    Route::get('/form/elements', function () {
        return view('pages/form-elements');
    });
    Route::get('/form/plugins', function () {
        return view('pages/form-plugins');
    });
    Route::get('/form/slider-switcher', function () {
        return view('pages/form-slider-switcher');
    });
    Route::get('/form/validation', function () {
        return view('pages/form-validation');
    });
    Route::get('/form/wizards', function () {
        return view('pages/form-wizards');
    });
    Route::get('/form/wizards-validation', function () {
        return view('pages/form-wizards-validation');
    });
    Route::get('/form/wysiwyg', function () {
        return view('pages/form-wysiwyg');
    });
    Route::get('/form/x-editable', function () {
        return view('pages/form-x-editable');
    });
    Route::get('/form/multiple-file-upload', function () {
        return view('pages/form-multiple-file-upload');
    });
    Route::get('/form/summernote', function () {
        return view('pages/form-summernote');
    });
    Route::get('/form/dropzone', function () {
        return view('pages/form-dropzone');
    });
    Route::get('/table/basic', function () {
        return view('pages/table-basic');
    });
    Route::get('/table/manage/default', function () {
        return view('pages/table-manage-default');
    });
    Route::get('/table/manage/autofill', function () {
        return view('pages/table-manage-autofill');
    });
    Route::get('/table/manage/buttons', function () {
        return view('pages/table-manage-buttons');
    });
    Route::get('/table/manage/colreorder', function () {
        return view('pages/table-manage-colreorder');
    });
    Route::get('/table/manage/fixed-column', function () {
        return view('pages/table-manage-fixed-column');
    });
    Route::get('/table/manage/fixed-header', function () {
        return view('pages/table-manage-fixed-header');
    });
    Route::get('/table/manage/keytable', function () {
        return view('pages/table-manage-keytable');
    });
    Route::get('/table/manage/responsive', function () {
        return view('pages/table-manage-responsive');
    });
    Route::get('/table/manage/rowreorder', function () {
        return view('pages/table-manage-rowreorder');
    });
    Route::get('/table/manage/scroller', function () {
        return view('pages/table-manage-scroller');
    });
    Route::get('/table/manage/select', function () {
        return view('pages/table-manage-select');
    });
    Route::get('/table/manage/combine', function () {
        return view('pages/table-manage-combine');
    });
    Route::get('/email-template/system', function () {
        return view('pages/email-template-system');
    });
    Route::get('/email-template/newsletter', function () {
        return view('pages/email-template-newsletter');
    });
    Route::get('/chart/flot', function () {
        return view('pages/chart-flot');
    });
    Route::get('/chart/morris', function () {
        return view('pages/chart-morris');
    });
    Route::get('/chart/js', function () {
        return view('pages/chart-js');
    });
    Route::get('/chart/d3', function () {
        return view('pages/chart-d3');
    });
    Route::get('/chart/apex', function () {
        return view('pages/chart-apex');
    });
    Route::get('/calendar', function () {
        return view('pages/calendar');
    });
    Route::get('/map/vector', function () {
        return view('pages/map-vector');
    });
    Route::get('/map/google', function () {
        return view('pages/map-google');
    });
    Route::get('/gallery/v1', function () {
        return view('pages/gallery-v1');
    });
    Route::get('/gallery/v2', function () {
        return view('pages/gallery-v2');
    });
    Route::get('/page-option/page-blank', function () {
        return view('pages/page-blank');
    });
    Route::get('/page-option/page-with-footer', function () {
        return view('pages/page-with-footer');
    });
    Route::get('/page-option/page-without-sidebar', function () {
        return view('pages/page-without-sidebar');
    });
    Route::get('/page-option/page-with-right-sidebar', function () {
        return view('pages/page-with-right-sidebar');
    });
    Route::get('/page-option/page-with-minified-sidebar', function () {
        return view('pages/page-with-minified-sidebar');
    });
    Route::get('/page-option/page-with-two-sidebar', function () {
        return view('pages/page-with-two-sidebar');
    });
    Route::get('/page-option/page-full-height', function () {
        return view('pages/page-full-height');
    });
    Route::get('/page-option/page-with-wide-sidebar', function () {
        return view('pages/page-with-wide-sidebar');
    });
    Route::get('/page-option/page-with-light-sidebar', function () {
        return view('pages/page-with-light-sidebar');
    });
    Route::get('/page-option/page-with-mega-menu', function () {
        return view('pages/page-with-mega-menu');
    });
    Route::get('/page-option/page-with-top-menu', function () {
        return view('pages/page-with-top-menu');
    });
    Route::get('/page-option/page-with-boxed-layout', function () {
        return view('pages/page-with-boxed-layout');
    });
    Route::get('/page-option/page-with-mixed-menu', function () {
        return view('pages/page-with-mixed-menu');
    });
    Route::get('/page-option/boxed-layout-with-mixed-menu', function () {
        return view('pages/page-boxed-layout-with-mixed-menu');
    });
    Route::get('/page-option/page-with-transparent-sidebar', function () {
        return view('pages/page-with-transparent-sidebar');
    });
    Route::get('/page-option/page-with-search-sidebar', function () {
        return view('pages/page-with-search-sidebar');
    });
    Route::get('/extra/timeline', function () {
        return view('pages/extra-timeline');
    });
    Route::get('/extra/coming-soon', function () {
        return view('pages/extra-coming-soon');
    });

for_web_interfece/app/Models/Employee/Employee.php
<?php

namespace App\Models\Employee;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getImageAttribute($value)
    {
        if ($value == null) {
            return null;
        }
        return asset($value);
    }

    public static function getEmployees($organization_id)
    {
        return self::where('organization_id', $organization_id)->get();
    }

    public function history()
    {
        return $this->hasMany(EmployeeHistory::class);
    }

    public function wanted(){
        return $this->belongsTo(Wanted::class);
    }
}

for_web_interfece/resources/views/project/employee-history.blade.php
@extends('layouts.default')

@section('title', 'Employee History')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-fixedcolumns-bs4/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
<!-- begin breadcrumb -->
<ol class="breadcrumb float-xl-right">
  <li class="breadcrumb-item"><a href="javascript:;">Dashboard</a></li>
  <li class="breadcrumb-item active">History of {{ $wanted->employee->name }}</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Wanted Employees' History</h1>
<!-- end page-header -->
<!-- begin row -->
<div class="row">
  <!-- begin col-10 -->
  <div class="col-xl-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <!-- begin panel-heading -->
      <div class="panel-heading">
        <h4 class="panel-title">Employee History</h4>
        <div class="panel-heading-btn">
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
              class="fa fa-expand"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
              class="fa fa-redo"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
              class="fa fa-minus"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i
              class="fa fa-times"></i></a>
        </div>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle">
          <thead>
            <tr>
              <th width="1%"></th>
              <th width="1%" data-orderable="false"></th>
              <th class="text-nowrap">Employee Name</th>
              <th class="text-nowrap">Territory</th>
              <th class="text-nowrap">Action Type</th>
              <th class="text-nowrap">Action Time</th>
              <th class="text-nowrap">Device</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($wanted->history as $index=>$item)
            <tr class="odd gradeX">
              <td width="1%" class="f-s-600 text-inverse">{{ $index+1 }}</td>
              <td width="1%" class="with-img"><img src="{{ $wanted->employee->image }}" class="img-rounded height-30" />
              </td>
              <td>{{ $wanted->employee->name }}</td>
              <td>{{ $item->device->territory->name }}</td>
              <td>{{ $item->device->action_type }}</td>
              <td>{{ $item->action_date }}</td>
              <td>{{ $item->device->name }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns/js/dataTables.fixedcolumns.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns-bs4/js/fixedcolumns.bootstrap4.min.js"></script>
<script src="/assets/js/demo/table-manage-fixed-columns.demo.js"></script>
@endpush

for_web_interfece/resources/views/project/employees.blade.php
@extends('layouts.default')

@section('title', 'Employees')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-fixedcolumns-bs4/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
<!-- begin breadcrumb -->
<ol class="breadcrumb float-xl-right">
  <li class="breadcrumb-item"><a href="javascript:;">Dashboard</a></li>
  <li class="breadcrumb-item active">Employees</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Employees</h1>
<!-- end page-header -->
<!-- begin row -->
<div class="row">
  <!-- begin col-10 -->
  <div class="col-xl-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <!-- begin panel-heading -->
      <div class="panel-heading">
        <h4 class="panel-title">Employees</h4>
        <div class="panel-heading-btn">
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
              class="fa fa-expand"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
              class="fa fa-redo"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
              class="fa fa-minus"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i
              class="fa fa-times"></i></a>
        </div>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <a href="#modal-without-animation" data-toggle="modal" class="btn btn-primary">Add New Employee</a>
        <table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle">
          <thead>
            <tr>
              <th width="1%"></th>
              <th width="1%" data-orderable="false"></th>
              <th class="text-nowrap">Employee Name</th>
              <th class="text-nowrap">Joined Date</th>
              <th class="text-nowrap"></th>
            </tr>
          </thead>
          <tbody>
            @foreach ($list as $index=>$item)
            <tr class="odd gradeX">
              <td width="1%" class="f-s-600 text-inverse">{{ $index+1 }}</td>
              <td width="1%" class="with-img"><img src="{{ $item->image }}" class="img-rounded height-30" />
              <td>{{ $item->name }}</td>
              <td>{{ $item->created_at }}</td>
              <td>
                <div class="d-flex flex-row-reverse">
                  <a href="javascript:;" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                  <a href="javascript:;" class="btn btn-primary mr-2"><i class="fa fa-pen"></i></a>
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->
@endsection

<div class="modal fade" id="modal-without-animation">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Select an Employee for searching</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <form action="{{ route('admin.add-employee') }}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
            <label for="name">Employee Name</label>
            <input type="text" id="name" name="name" class="form-control">
          </div>
          <div class="form-group">
            <input type="file" id="image" name="image">
          </div>
          <button class="btn btn-primary pull-right mt-2">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns/js/dataTables.fixedcolumns.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns-bs4/js/fixedcolumns.bootstrap4.min.js"></script>
<script src="/assets/js/demo/table-manage-fixed-columns.demo.js"></script>
@endpush

for_web_interfece/resources/views/project/report.blade.php
@extends('layouts.default')

@section('title', 'Employees Report')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-fixedcolumns-bs4/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
<!-- begin breadcrumb -->
<ol class="breadcrumb float-xl-right">
  <li class="breadcrumb-item"><a href="javascript:;">Dashboard</a></li>
  <li class="breadcrumb-item active">Employees Report</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Employees Report</h1>
<!-- end page-header -->
<!-- begin row -->
<div class="row">
  <!-- begin col-10 -->
  <div class="col-xl-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <!-- begin panel-heading -->
      <div class="panel-heading">
        <h4 class="panel-title">Employees Report</h4>
        <div class="panel-heading-btn">
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
              class="fa fa-expand"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
              class="fa fa-redo"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
              class="fa fa-minus"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i
              class="fa fa-times"></i></a>
        </div>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle">
          <thead>
            <tr>
              <th width="1%"></th>
              <th width="1%" data-orderable="false"></th>
              <th class="text-nowrap">Employee Name</th>
              <th class="text-nowrap">Date</th>
              <th class="text-nowrap">Fork Hour</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($list as $index => $item)
            <tr class="odd gradeX">
              <td width="1%" class="f-s-600 text-inverse">{{ $index+1 }}</td>
              <td width="1%" class="with-img"><img src="{{ $item->employee->image }}" class="img-rounded height-30" />
              </td width="3%">
              <td>{{ $item->employee->name }}</td>
              <td>{{ $item->date }}</td>
              <td>{{ $item->work }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns/js/dataTables.fixedcolumns.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns-bs4/js/fixedcolumns.bootstrap4.min.js"></script>
<script src="/assets/js/demo/table-manage-fixed-columns.demo.js"></script>
@endpush

for_web_interfece/resources/views/project/wanteds.blade.php
@extends('layouts.default')

@section('title', 'Wanted Employees')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-fixedcolumns-bs4/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
<!-- begin breadcrumb -->
<ol class="breadcrumb float-xl-right">
  <li class="breadcrumb-item"><a href="javascript:;">Dashboard</a></li>
  <li class="breadcrumb-item active">Wanted Employees</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Wanted Employees</h1>
<!-- end page-header -->
<!-- begin row -->
<div class="row">
  <!-- begin col-10 -->
  <div class="col-xl-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <!-- begin panel-heading -->
      <div class="panel-heading">
        <h4 class="panel-title">Wanted Employees</h4>
        <div class="panel-heading-btn">
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
              class="fa fa-expand"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
              class="fa fa-redo"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
              class="fa fa-minus"></i></a>
          <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i
              class="fa fa-times"></i></a>
        </div>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <a href="#modal-without-animation" data-toggle="modal" class="btn btn-primary">Search an Employee</a>
        <table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle">
          <thead>
            <tr>
              <th width="1%"></th>
              <th width="1%" data-orderable="false"></th>
              <th class="text-nowrap">Employee Name</th>
              <th class="text-nowrap">Date</th>
              <th class="text-nowrap">Status</th>
              <th class="text-nowrap"></th>
            </tr>
          </thead>
          <tbody>
            @foreach ($list as $index=>$item)

            <tr class="odd gradeX">
              <td width="1%" class="f-s-600 text-inverse">{{ $index+1 }}</td>
              <td width="1%" class="with-img"><img src="{{ $item->employee->image }}" class="img-rounded height-30" />
              </td width="3%">
              <td>{{ $item->employee->name }}</td>
              <td>{{ $item->date }}</td>
              <td>
                <center>
                  @if (!$item->status)
                  <a href="javascript:;" class="btn btn-success items-center">Completed</a>
                  @else
                  <a href="javascript:;" class="btn btn-warning items-center">Searching Continue</a>
                  @endif
                </center>
              </td>
              <td>
                <center>
                  <a href="{{ route('admin.employee-history', $item->id) }}" class="btn btn-info"><i
                      class="fa fa-eye"></i></a>
                  @if ($item->status)
                  <a href="{{ route('admin.stop-searching', $item->id) }}" class="btn btn-danger"><i
                      class="fa fa-square"></i></a>
                  @endif
                </center>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->

<div class="modal fade" id="modal-without-animation">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Select an Employee for searching</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <form action="{{ route('admin.search') }}" method="POST" class="d-flex">
          @csrf
          <select name="id" class="form-control mr-2">
            @foreach ($employees as $item)
            <option value="{{ $item->id }}">{{ $item->name }}</option>
            @endforeach
          </select>

          <button class="btn btn-primary">Search</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns/js/dataTables.fixedcolumns.min.js"></script>
<script src="/assets/plugins/datatables.net-fixedcolumns-bs4/js/fixedcolumns.bootstrap4.min.js"></script>
<script src="/assets/js/demo/table-manage-fixed-columns.demo.js"></script>
@endpush